"""Dev seed projects — loaded once when data/projects/ is empty."""

from __future__ import annotations

from typing import Any

CATALOG_PIPELINE_NODES: list[dict[str, Any]] = [
    {
        "id": "cp-note-welcome",
        "kind": "sticky",
        "role": "note",
        "label": "Workflow ready",
        "noteBody": (
            "✅ This demo workflow is ready to use\n✨ Supports **markdown**, *italic*, and lists"
        ),
        "noteColor": "purple",
        "noteWidth": 300,
        "noteHeight": 120,
        "x": 40,
        "y": 24,
    },
    {
        "id": "cp-schedule",
        "kind": "schedule",
        "role": "trigger",
        "label": "Daily catalog sync",
        "subtitle": "cron: 0 6 * * *",
        "status": "online",
        "x": 40,
        "y": 200,
    },
    {
        "id": "cp-agent",
        "kind": "agent",
        "role": "agent",
        "label": "Gateway agent",
        "subtitle": "scrape-assistant",
        "detail": "postgres-catalog",
        "host": "gateway-tools",
        "status": "online",
        "agentPrompt": (
            "Review scraped catalog items and summarize changes for export.\n"
            "Use **batch-ops** when the operator asks for bulk actions."
        ),
        "x": 280,
        "y": 180,
    },
    {
        "id": "cp-scrape",
        "kind": "scrape",
        "role": "action",
        "label": "Batch scrape",
        "subtitle": "1688 · taobao",
        "status": "online",
        "options": {"marketplace": "both"},
        "x": 560,
        "y": 180,
    },
    {
        "id": "cp-export",
        "kind": "export",
        "role": "action",
        "label": "Export listings",
        "subtitle": "shopee · lazada",
        "host": "export-review",
        "status": "online",
        "options": {"exportTarget": "both"},
        "x": 800,
        "y": 180,
    },
    {
        "id": "cp-model",
        "kind": "agent",
        "role": "config",
        "label": "Gateway LLM",
        "subtitle": "openai: gpt-4o",
        "x": 120,
        "y": 400,
    },
    {
        "id": "cp-postgres",
        "kind": "postgres",
        "role": "config",
        "label": "Postgres",
        "subtitle": "postgres: catalog",
        "host": "postgres.internal",
        "detail": "catalog-db volume",
        "status": "online",
        "x": 280,
        "y": 400,
    },
    {
        "id": "cp-redis",
        "kind": "redis",
        "role": "config",
        "label": "Redis",
        "subtitle": "redis: queue",
        "host": "redis.internal",
        "detail": "1/1 replicas active",
        "status": "online",
        "x": 440,
        "y": 400,
    },
]

CATALOG_PIPELINE_EDGES: list[dict[str, Any]] = [
    {"id": "cp-e1", "from": "cp-schedule", "to": "cp-agent", "kind": "main"},
    {"id": "cp-e2", "from": "cp-agent", "to": "cp-scrape", "kind": "main"},
    {"id": "cp-e3", "from": "cp-scrape", "to": "cp-export", "kind": "main"},
    {"id": "cp-e4", "from": "cp-model", "to": "cp-agent", "kind": "config", "slotIndex": 0},
    {"id": "cp-e5", "from": "cp-postgres", "to": "cp-agent", "kind": "config", "slotIndex": 1},
    {"id": "cp-e6", "from": "cp-redis", "to": "cp-agent", "kind": "config", "slotIndex": 2},
]

TELEGRAM_OPS_NODES: list[dict[str, Any]] = [
    {
        "id": "to-webhook",
        "kind": "webhook",
        "role": "trigger",
        "label": "Telegram control chat",
        "subtitle": "integrate: telegram",
        "host": "/integrate/telegram/inbound",
        "status": "online",
        "options": {"webhookActive": True},
        "x": 40,
        "y": 200,
    },
    {
        "id": "to-agent",
        "kind": "agent",
        "role": "agent",
        "label": "Gateway agent",
        "subtitle": "agent-control",
        "detail": "postgres-chat-memory",
        "host": "gateway-tools",
        "status": "online",
        "x": 300,
        "y": 180,
    },
    {
        "id": "to-notify",
        "kind": "notify",
        "role": "action",
        "label": "Send summary",
        "subtitle": "telegram: ops-chat",
        "host": "integrate-notify",
        "status": "online",
        "x": 580,
        "y": 180,
    },
    {
        "id": "to-model",
        "kind": "agent",
        "role": "config",
        "label": "Gateway LLM",
        "subtitle": "openai: gpt-4o-mini",
        "x": 140,
        "y": 400,
    },
    {
        "id": "to-postgres",
        "kind": "postgres",
        "role": "config",
        "label": "Postgres",
        "subtitle": "postgres: sessions",
        "host": "postgres.internal",
        "detail": "chat-memory volume",
        "status": "online",
        "x": 300,
        "y": 400,
    },
    {
        "id": "to-redis",
        "kind": "redis",
        "role": "config",
        "label": "Redis",
        "subtitle": "redis: rate-limit",
        "host": "redis.internal",
        "detail": "1/1 replicas active",
        "status": "online",
        "x": 460,
        "y": 400,
    },
]

TELEGRAM_OPS_EDGES: list[dict[str, Any]] = [
    {"id": "to-e1", "from": "to-webhook", "to": "to-agent", "kind": "main"},
    {"id": "to-e2", "from": "to-agent", "to": "to-notify", "kind": "main"},
    {"id": "to-e3", "from": "to-model", "to": "to-agent", "kind": "config", "slotIndex": 0},
    {"id": "to-e4", "from": "to-postgres", "to": "to-agent", "kind": "config", "slotIndex": 1},
    {"id": "to-e5", "from": "to-redis", "to": "to-agent", "kind": "config", "slotIndex": 2},
]

STAGING_INGEST_NODES: list[dict[str, Any]] = [
    {
        "id": "si-scrape",
        "kind": "scrape",
        "role": "action",
        "label": "1688 ingest",
        "subtitle": "1688: category-feed",
        "status": "offline",
        "x": 80,
        "y": 180,
    },
    {
        "id": "si-condition",
        "kind": "condition",
        "role": "action",
        "label": "Catalog threshold",
        "subtitle": "if count > 100",
        "status": "online",
        "x": 320,
        "y": 180,
    },
    {
        "id": "si-agent",
        "kind": "agent",
        "role": "agent",
        "label": "Gateway agent",
        "subtitle": "batch-ops",
        "host": "gateway-tools",
        "status": "online",
        "x": 560,
        "y": 180,
    },
    {
        "id": "si-postgres",
        "kind": "postgres",
        "role": "config",
        "label": "Postgres",
        "subtitle": "postgres: staging",
        "host": "postgres.internal",
        "detail": "staging-db volume",
        "status": "online",
        "x": 520,
        "y": 400,
    },
    {
        "id": "si-github",
        "kind": "github",
        "role": "action",
        "label": "Deploy hook",
        "subtitle": "main branch",
        "host": "github.com/cross-border/staging",
        "status": "offline",
        "x": 800,
        "y": 180,
    },
]

STAGING_INGEST_EDGES: list[dict[str, Any]] = [
    {"id": "si-e1", "from": "si-scrape", "to": "si-condition", "kind": "main"},
    {"id": "si-e2", "from": "si-condition", "to": "si-agent", "kind": "main"},
    {"id": "si-e3", "from": "si-agent", "to": "si-github", "kind": "main"},
    {"id": "si-e4", "from": "si-postgres", "to": "si-agent", "kind": "config", "slotIndex": 1},
]

DEV_SEED_PROJECTS: list[dict[str, Any]] = [
    {
        "id": "catalog-pipeline",
        "name": "Catalog pipeline",
        "environment": "production",
        "updated_at": "2026-05-28T14:20:00Z",
        "description": (
            "Scheduled scrape, agent review, and marketplace export for the product catalog."
        ),
        "nodes": CATALOG_PIPELINE_NODES,
        "edges": CATALOG_PIPELINE_EDGES,
    },
    {
        "id": "telegram-ops",
        "name": "Telegram ops",
        "environment": "production",
        "updated_at": "2026-05-27T09:10:00Z",
        "description": (
            "Control chat for gateway agent — schedules, health checks, and operator alerts."
        ),
        "nodes": TELEGRAM_OPS_NODES,
        "edges": TELEGRAM_OPS_EDGES,
    },
    {
        "id": "staging-ingest",
        "name": "Staging ingest",
        "environment": "staging",
        "updated_at": "2026-05-20T18:00:00Z",
        "description": "Partial staging flow — missing model slot and one offline scrape step.",
        "nodes": STAGING_INGEST_NODES,
        "edges": STAGING_INGEST_EDGES,
    },
]
