export const queryKeys = {
  health: ['health'] as const,
  panelAccess: ['panel', 'access'] as const,
  logs: (category: string, q: string, limit: number, offset: number) =>
    ['logs', category, q, limit, offset] as const,
  config: ['config'] as const,
  stats: ['stats'] as const,
  batches: (limit = 50) => ['batches', { limit }] as const,
  batch: (id: string) => ['batches', id] as const,
  batchStatus: (id: string) => ['jobs', id, 'status'] as const,
  batchResult: (id: string) => ['jobs', id, 'result'] as const,
  panelConfig: ['config', 'panel'] as const,
  llmHealth: ['ai', 'health'] as const,
  llmProviders: ['ai', 'providers'] as const,
  runtimeStatus: ['runtime', 'status'] as const,
  hardwareMonitor: ['monitor', 'hardware'] as const,
  monitorStatus: ['monitor', 'status'] as const,
  marketplaces: ['export', 'marketplaces'] as const,
  gatewayStatus: ['gateway', 'status'] as const,
  gatewayUpdateStatus: ['gateway', 'update', 'status'] as const,
  gatewayPrompts: ['gateway', 'prompts'] as const,
  gatewaySkills: ['gateway', 'skills'] as const,
  gatewayRules: ['gateway', 'rules'] as const,
  gatewayRule: (ruleId: string) => ['gateway', 'rules', ruleId] as const,
  gatewaySkillRegistry: (params: Record<string, string | number | null | undefined>) =>
    ['gateway', 'skills', 'registry', params] as const,
  gatewayTools: ['gateway', 'tools'] as const,
  gatewayWorkflows: ['gateway', 'workflows'] as const,
  gatewayTelegram: ['gateway', 'telegram'] as const,
  gatewayChannel: (channelId: string) => ['gateway', 'channels', channelId] as const,
  gatewayChannels: ['gateway', 'channels'] as const,
  agentSchedules: ['gateway', 'schedules'] as const,
  agentRuns: ['gateway', 'runs'] as const,
  serviceOverview: ['service', 'overview'] as const,
  serviceSupport: ['service', 'support'] as const,
  networkAccess: ['deploy', 'network'] as const,
  panelSecurity: ['deploy', 'security'] as const,
  proxyStatus: ['config', 'proxy', 'status'] as const,
  serviceScheduler: ['service', 'scheduler'] as const,
  products: (limit = 100, offset = 0) => ['products', { limit, offset }] as const,
  product: (id: number) => ['products', id] as const,
  files: ['files'] as const,
  storeEnvironment: ['store', 'environment'] as const,
  storeCatalog: ['store', 'catalog'] as const,
  storeInstalled: ['store', 'installed'] as const,
  storePlugin: (id: string) => ['store', 'plugin', id] as const,
  dockerStatus: ['docker', 'status'] as const,
  dockerConfig: ['docker', 'config'] as const,
  dockerContainers: ['docker', 'containers'] as const,
  dockerHub: (q: string) => ['docker', 'hub', q] as const,
  firewallStatus: ['firewall', 'status'] as const,
  firewallRules: ['firewall', 'rules'] as const,
  firewallGroups: ['firewall', 'groups'] as const,
  firewallExport: ['firewall', 'export'] as const,
}
