export const queryKeys = {
  health: ['health'] as const,
  panelAccess: ['panel', 'access'] as const,
  logs: (category: string, q: string, limit: number, offset: number) =>
    ['logs', category, q, limit, offset] as const,
  config: ['config'] as const,
  stats: ['stats'] as const,
  batches: (limit = 50) => ['batches', { limit }] as const,
  batch: (id: string) => ['batches', id] as const,
  batchStatus: (id: string) => ['jobs', id, 'status'] as const,
  batchResult: (id: string) => ['jobs', id, 'result'] as const,
  aiConfig: ['ai', 'config'] as const,
  panelConfig: ['config', 'panel'] as const,
  llmHealth: ['ai', 'health'] as const,
  runtimeStatus: ['runtime', 'status'] as const,
  hardwareMonitor: ['monitor', 'hardware'] as const,
  monitorStatus: ['monitor', 'status'] as const,
  marketplaces: ['export', 'marketplaces'] as const,
  gatewayStatus: ['gateway', 'status'] as const,
  gatewayPrompts: ['gateway', 'prompts'] as const,
  gatewaySkills: ['gateway', 'skills'] as const,
  gatewayTools: ['gateway', 'tools'] as const,
  gatewayWorkflows: ['gateway', 'workflows'] as const,
  agentSchedules: ['gateway', 'schedules'] as const,
  agentRuns: ['gateway', 'runs'] as const,
  serviceOverview: ['service', 'overview'] as const,
  serviceSupport: ['service', 'support'] as const,
  serviceScheduler: ['service', 'scheduler'] as const,
  products: (limit = 100, offset = 0) => ['products', { limit, offset }] as const,
  product: (id: number) => ['products', id] as const,
  files: ['files'] as const,
  storeEnvironment: ['store', 'environment'] as const,
  storeCatalog: ['store', 'catalog'] as const,
  storeInstalled: ['store', 'installed'] as const,
  storePlugin: (id: string) => ['store', 'plugin', id] as const,
}
